export const ValidationIdentifiers = {
    // Carteira
    CARTEIRA_CREATE: 'CARTEIRA_CREATE',
    CARTEIRA_UPDATE: 'CARTEIRA_UPDATE',
    CARTEIRA_DELETE: 'CARTEIRA_DELETE',
    
    // Cedente
    CEDENTE_CREATE: 'CEDENTE_CREATE',
    CEDENTE_UPDATE: 'CEDENTE_UPDATE',
    CEDENTE_DELETE: 'CEDENTE_DELETE',
    
    // Processo
    PROCESSO_CREATE: 'PROCESSO_CREATE',
    PROCESSO_UPDATE: 'PROCESSO_UPDATE',
    PROCESSO_DELETE: 'PROCESSO_DELETE',
    
    // Parte Processo
    PARTE_PROCESSO_CREATE: 'PARTE_PROCESSO_CREATE',
    PARTE_PROCESSO_UPDATE: 'PARTE_PROCESSO_UPDATE',
    PARTE_PROCESSO_DELETE: 'PARTE_PROCESSO_DELETE',
    
    // User
    USER_CREATE: 'USER_CREATE',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
  };